

name: Testinng and Packaging
on:
  - push
jobs:
  test_ubuntu:
    name: Test_ubuntu
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          - version: "3.10"
          - version: "3.9"
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4.0.0
        with:
          python-version: ${{ matrix.python.version }}

      - name: Install pytest
        run: python -m pip install pytest pytest-cov numpy scipy .

      - name: Run pytest
        run: pytest --cov=lowrankdensity
        working-directory: . # You don't need this in your package

  test_macos:
    name: Test_MacOS
    runs-on: macos-latest
    strategy:
      matrix:
        python:
          - version: "3.10"
          - version: "3.9"
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4.0.0
        with:
          python-version: ${{ matrix.python.version }}

      - name: Install pytest
        run: python -m pip install pytest pytest-cov numpy scipy .

      - name: Run pytest
        run: pytest --cov=lowrankdensity
        working-directory: . # You don't need this in your package
  test_windows:
    name: Test_Windows
    runs-on: windows-latest
    strategy:
      matrix:
        python:
          - version: "3.10"
          - version: "3.9"
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4.0.0
        with:
          python-version: ${{ matrix.python.version }}

      - name: Install pytest
        run: python -m pip install pytest pytest-cov numpy scipy .

      - name: Run pytest
        run: pytest --cov=lowrankdensity
        working-directory: . # You don't need this in your package
  build_source_dist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4.0.0
        with:
          python-version: "3.10"

      - name: Install build
        run: python -m pip install build

      - name: Run build
        # run: python -m build --sdist --wheel
        run: python -m build
        working-directory: . # You don't need this in your package

      - uses: actions/upload-artifact@v3
        with:
          path: ./dist/*.tar.gz

  build_wheels:
    name: Build wheels
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4.0.0
        with:
          python-version: "3.10"

      - name: Install build
        run: python -m pip install build

      - name: Run build
        run: python -m build
        working-directory: . # You don't need this in your package

      - uses: actions/upload-artifact@v3
        with:
          path: ./dist/*.whl  

  
